# Generated by Django 2.0.2 on 2018-02-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('employeeID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(default='CSE', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('employeeID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sciJournals', models.IntegerField(default=0)),
                ('unpaidScop', models.IntegerField(default=0)),
                ('paidScop', models.IntegerField(default=0)),
                ('otherJournals', models.IntegerField(default=0)),
                ('confAtten', models.IntegerField(default=0)),
                ('seminarAtten', models.IntegerField(default=0)),
                ('workshopAtten', models.IntegerField(default=0)),
                ('trainProAtten', models.IntegerField(default=0)),
                ('confOrg', models.IntegerField(default=0)),
                ('workshopOrg', models.IntegerField(default=0)),
                ('seminarOrg', models.IntegerField(default=0)),
            ],
        ),
    ]
