# Generated by Django 2.0.2 on 2018-07-11 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencesAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('paperTitle', models.CharField(max_length=50, verbose_name='Paper Title')),
                ('name', models.CharField(max_length=50)),
                ('total_duration', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('orgInstitute', models.CharField(max_length=50, verbose_name='Organising Institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConferencesOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_duration', models.IntegerField()),
                ('orgInstitute', models.CharField(max_length=50, verbose_name='Organising Institute')),
                ('fundingAgency', models.CharField(max_length=100, verbose_name='Funding Agency')),
                ('role', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherJournals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('corresAuthors', models.CharField(max_length=100, verbose_name='Corresponding Authors')),
                ('paperTitle', models.CharField(max_length=50, verbose_name='Paper Title')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('impactFac', models.CharField(max_length=50, verbose_name='Impact Factor')),
                ('volume', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50, verbose_name='PP')),
                ('year', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaidScopus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('corresAuthors', models.CharField(max_length=100, verbose_name='Corresponding Authors')),
                ('paperTitle', models.CharField(max_length=50, verbose_name='Paper Title')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('impactFac', models.CharField(max_length=50, verbose_name='Impact Factor')),
                ('volume', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50, verbose_name='PP')),
                ('year', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dummy', max_length=50, verbose_name='Name')),
                ('dept', models.CharField(default='CSE', max_length=20, verbose_name='Department')),
                ('phone', models.CharField(default='1234567890', max_length=15, verbose_name='Phone')),
                ('desgn', models.CharField(default='staff', max_length=20, verbose_name='Designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL, verbose_name='Employee ID')),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='SCIJournals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('corresAuthors', models.CharField(max_length=100, verbose_name='Corresponding Authors')),
                ('paperTitle', models.CharField(max_length=50, verbose_name='Paper Title')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('impactFac', models.CharField(max_length=50, verbose_name='Impact Factor')),
                ('volume', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50, verbose_name='PP')),
                ('year', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarsAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('paperTitle', models.CharField(max_length=50, verbose_name='Paper Title')),
                ('name', models.CharField(max_length=50)),
                ('total_duration', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('orgInstitute', models.CharField(max_length=50, verbose_name='Organising Institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarsOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_duration', models.IntegerField()),
                ('orgInstitute', models.CharField(max_length=50, verbose_name='Organising Institute')),
                ('fundingAgency', models.CharField(max_length=100, verbose_name='Funding Agency')),
                ('role', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_duration', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('orgInstitute', models.CharField(max_length=50, verbose_name='Organising Institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnpaidScopus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('corresAuthors', models.CharField(max_length=100, verbose_name='Corresponding Authors')),
                ('paperTitle', models.CharField(max_length=50, verbose_name='Paper Title')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('impactFac', models.CharField(max_length=50, verbose_name='Impact Factor')),
                ('volume', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50, verbose_name='PP')),
                ('year', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopsAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_duration', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('orgInstitute', models.CharField(max_length=50, verbose_name='Organising Institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopsOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_duration', models.IntegerField()),
                ('orgInstitute', models.CharField(max_length=50, verbose_name='Organising Institute')),
                ('fundingAgency', models.CharField(max_length=100, verbose_name='Funding Agency')),
                ('role', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
