# Generated by Django 2.0.2 on 2018-02-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE_Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencesAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('paperTitle', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('place', models.CharField(max_length=100)),
                ('orgInstitute', models.CharField(max_length=50)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='ConferencesOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('orgInstitute', models.CharField(max_length=50)),
                ('fundingAgency', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='OtherJournals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('corresAuthors', models.CharField(max_length=100)),
                ('paperTitle', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('impactFac', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='PaidScopus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('corresAuthors', models.CharField(max_length=100)),
                ('paperTitle', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('impactFac', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='SCIJournals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('corresAuthors', models.CharField(max_length=100)),
                ('paperTitle', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('impactFac', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarsAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('paperTitle', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('place', models.CharField(max_length=100)),
                ('orgInstitute', models.CharField(max_length=50)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarsOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('orgInstitute', models.CharField(max_length=50)),
                ('fundingAgency', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('place', models.CharField(max_length=100)),
                ('orgInstitute', models.CharField(max_length=50)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='UnpaidScopus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('corresAuthors', models.CharField(max_length=100)),
                ('paperTitle', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('impactFac', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopsAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('place', models.CharField(max_length=100)),
                ('orgInstitute', models.CharField(max_length=50)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopsOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('orgInstitute', models.CharField(max_length=50)),
                ('fundingAgency', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE_Department.User')),
            ],
        ),
    ]
