# Generated by Django 2.0.2 on 2018-02-11 08:07

import CSE_Department.utils
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE_Department', '0007_auto_20180210_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=CSE_Department.utils.AutoOnetoOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
