# Generated by Django 2.0.2 on 2018-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE_Department', '0009_auto_20180212_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desgn',
            field=models.CharField(default='staff', max_length=20),
        ),
    ]
