# Generated by Django 2.0.2 on 2018-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE_Department', '0010_profile_desgn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherjournals',
            name='year',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='paidscopus',
            name='year',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='scijournals',
            name='year',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='unpaidscopus',
            name='year',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
