# Generated by Django 2.0.2 on 2018-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE_Department', '0012_auto_20180307_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherjournals',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paidscopus',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='scijournals',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unpaidscopus',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
