# Generated by Django 2.0.2 on 2018-03-13 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE_Department', '0014_auto_20180307_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesattended',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conferencesorg',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(default='CSE', max_length=20, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desgn',
            field=models.CharField(default='staff', max_length=20, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='dummy', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='1234567890', max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='seminarsattended',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seminarsorg',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingprogattended',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workshopsattended',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workshopsorg',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
